
services:
  db:
    image: postgres:12.18
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ejemplo
    container_name: postgresuv

  tomcat:
    image: tomcat:9.0
    container_name: tomcat-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ejemplo
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/local/tomcat/webapps/api
    command: /bin/bash -c "cp /usr/local/tomcat/webapps/api.war /usr/local/tomcat/webapps/ROOT.war && catalina.sh run"

  angular:
    image: node:14
    container_name: angular-frontend
    working_dir: /app
    command: /bin/bash -c "npm install && npm run start"
    ports:
      - "4200:4200"
    depends_on:
      - tomcat
    volumes:
      - ./frontend:/app
